site_name: 'spikey-api'
repo_url: https://github.com/cohen990/backstage-kroki-spike-doc-providing-repo
plugins:
  - techdocs-core
  - kroki
      ServerURL: localhost:8000

nav:
  - 'General':
      - 'md file': some-markdown.md
      - 'puml': testing-kroki.md
  - 'General Engineering':
    - 'external': https://www.google.com
