site_name: 'spikey-api'
repo_url: https://github.com/cohen990/backstage-kroki-spike-doc-providing-repo
plugins:
  - techdocs-core
  - kroki:
      ServerURL:
        'http://localhost:8000' 
      EnableMermaid:
        True

nav:
  - 'General':
      - 'md file': some-markdown.md
      - 'testing-kroki': testing-kroki.md
      - 'testing-kroki-with-giant-file': complex-graphviz.md
  - 'General Engineering':
    - 'external': https://www.google.com
