site_name: 'spikey-api'
repo_url: https://github.com/cohen990/backstage-kroki-spike-doc-providing-repo
plugins:
  - techdocs-core

nav:
  - Home: index.md
  - 'General':
    - 'some external docs': https://www.google.com
  - 'General Engineering':
      - 'some markdown file': 'some-markdown.md'
